insert into Gakusei values(98101,'HK', 'Yamada', 'A');
insert into Gakusei values(98102,'TN', 'Hatoyama', 'B');
insert into Gakusei values(98103,'YM', 'Sakado', 'A');
insert into Gakusei values(98104,'HN', 'Kawagoe', 'C');

insert into Rishu values(98101, 'CS101', 'A');
insert into Rishu values(98101, 'CS102', 'B');
insert into Rishu values(98102, 'CS101', 'B');
insert into Rishu values(98103, 'CS103', 'C');
